name: Get latest personal data

on:
  workflow_dispatch:
  push:
  schedule:
    - cron:  '0 0 * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.9
    - uses: actions/cache@v2
      name: Configure pip caching
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        alias pip3.9='python -m pip'
        pip install -r requirements.txt
    - name: Get latest data
      run: |
        curl https://api.ashish.me/movies | jq . > movies.json
        curl https://api.ashish.me/shows | jq . > shows.json
        curl https://api.ashish.me/books | jq . > books.json
        curl https://api.ashish.me/todos | jq . > todos.json
        curl https://api.ashish.me/listens | jq . > listens.json
    - name: Commit and push if s changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Latest data: ${timestamp}" || exit 0
        git push
    - name: Create db
      run: |
        sqlite-utils insert ashish.db movies movies.json --pk=id
        sqlite-utils insert ashish.db shows shows.json --pk=id
        sqlite-utils insert ashish.db books books.json --pk=id
        sqlite-utils insert ashish.db todos todos.json --pk=id
        sqlite-utils insert ashish.db listens listens.json --pk=id
    - name: Deploy to Vercel
      env:
        VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
      run: |-
        alias pip3.9='python -m pip'
        datasette publish vercel ashish.db \
          --token $VERCEL_TOKEN \
          --branch 0.64.x \
          --project ashish-db \
          --metadata .github/metadata.yaml \
          --vercel-json .github/vercel.json \
          --install datasette-template-sql \
          --install "datasette-atom>=0.7" \
          --install datasette-json-html \
          --install beautifulsoup4 \
          --install datasette-debug-asgi \
          --install "datasette-graphql>=0.12" \
          --install datasette-media \
          --template-dir .github/templates \
          --public
